"""全国の灯台カードデータをDBに初期投入するスクリプト。"""
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from app.database import SessionLocal, engine, Base
from app.models import user, lighthouse, user_card  # noqa: F401
from app.models.lighthouse import Lighthouse

Base.metadata.create_all(bind=engine)

LIGHTHOUSES = [
    # ── 北海道・東北 ──────────────────────────────────────────────────────
    {
        "id": 1,
        "name": "納沙布岬灯台",
        "name_kana": "のさっぷみさきとうだい",
        "region": "北海道・東北",
        "prefecture": "北海道",
        "latitude": 43.3956,
        "longitude": 145.8156,
        "description": "日本最東端に位置する灯台。1872年（明治5年）初点灯。北方領土を望む最東端の岬に立ち、霧の多い海域を照らし続けている。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/01kanku/hakodate/lighthouse/nosappu.html",
        "qr_url_pattern": "nosappu",
        "established_year": 1872,
        "is_climbable": False,
    },
    {
        "id": 2,
        "name": "恵山岬灯台",
        "name_kana": "えさんみさきとうだい",
        "region": "北海道・東北",
        "prefecture": "北海道",
        "latitude": 41.8067,
        "longitude": 141.1783,
        "description": "津軽海峡に面した岬に建つ灯台。活火山・恵山の麓に位置し、海峡を往来する船舶の安全を守る。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/01kanku/hakodate/lighthouse/esan.html",
        "qr_url_pattern": "esan",
        "established_year": 1890,
        "is_climbable": False,
    },
    {
        "id": 3,
        "name": "尻屋崎灯台",
        "name_kana": "しりやざきとうだい",
        "region": "北海道・東北",
        "prefecture": "青森県",
        "latitude": 41.4283,
        "longitude": 141.4578,
        "description": "本州最北東端に建つ白亜の灯台。寒立馬が放牧される荒涼とした岬に立ち、登れる灯台として親しまれている。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/02kanku/lighthouse/shiriyazaki.html",
        "qr_url_pattern": "shiriyazaki",
        "established_year": 1876,
        "is_climbable": True,
    },
    {
        "id": 4,
        "name": "龍飛埼灯台",
        "name_kana": "たっぴさきとうだい",
        "region": "北海道・東北",
        "prefecture": "青森県",
        "latitude": 41.2544,
        "longitude": 140.3494,
        "description": "津軽半島最北端の龍飛岬に建つ灯台。強風で知られる岬に立ち、津軽海峡の船舶を導く。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/02kanku/lighthouse/tappisaki.html",
        "qr_url_pattern": "tappisaki",
        "established_year": 1932,
        "is_climbable": False,
    },
    {
        "id": 5,
        "name": "金華山灯台",
        "name_kana": "きんかさんとうだい",
        "region": "北海道・東北",
        "prefecture": "宮城県",
        "latitude": 38.2964,
        "longitude": 141.5664,
        "description": "牡鹿半島沖の金華山島に建つ灯台。神聖な島として知られ、三陸沿岸を航行する船舶を見守る。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/02kanku/lighthouse/kinkasan.html",
        "qr_url_pattern": "kinkasan",
        "established_year": 1876,
        "is_climbable": False,
    },
    # ── 関東・北陸・東海 ─────────────────────────────────────────────────
    {
        "id": 6,
        "name": "観音埼灯台",
        "name_kana": "かんのんざきとうだい",
        "region": "関東・北陸・東海",
        "prefecture": "神奈川県",
        "latitude": 35.6556,
        "longitude": 139.7747,
        "description": "日本初の西洋式灯台。1869年（明治2年）に点灯。東京湾の入口を守り、150年以上の歴史を持つ登れる灯台。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/03kanku/lighthouse/kannonzaki.html",
        "qr_url_pattern": "kannonzaki",
        "established_year": 1869,
        "is_climbable": True,
    },
    {
        "id": 7,
        "name": "犬吠埼灯台",
        "name_kana": "いぬぼうさきとうだい",
        "region": "関東・北陸・東海",
        "prefecture": "千葉県",
        "latitude": 35.7076,
        "longitude": 140.8709,
        "description": "本州最東端に近い岬の灯台。1874年（明治7年）初点灯。英国人技師が設計した白亜の灯台で、世界灯台100選に選ばれている。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/03kanku/lighthouse/inubosaki.html",
        "qr_url_pattern": "inubosaki",
        "established_year": 1874,
        "is_climbable": True,
    },
    {
        "id": 8,
        "name": "野島埼灯台",
        "name_kana": "のじまさきとうだい",
        "region": "関東・北陸・東海",
        "prefecture": "千葉県",
        "latitude": 34.8997,
        "longitude": 139.8828,
        "description": "房総半島最南端に建つ灯台。1870年（明治3年）初点灯。相模湾と太平洋の境界を守る登れる灯台。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/03kanku/lighthouse/nojima.html",
        "qr_url_pattern": "nojima",
        "established_year": 1870,
        "is_climbable": True,
    },
    {
        "id": 9,
        "name": "石廊崎灯台",
        "name_kana": "いろうざきとうだい",
        "region": "関東・北陸・東海",
        "prefecture": "静岡県",
        "latitude": 34.5992,
        "longitude": 138.8481,
        "description": "伊豆半島最南端の断崖に建つ灯台。荒波が打ち寄せる岬の先端に立ち、太平洋を行き交う船舶を導く。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/03kanku/lighthouse/irozaki.html",
        "qr_url_pattern": "irozaki",
        "established_year": 1871,
        "is_climbable": False,
    },
    {
        "id": 10,
        "name": "御前崎灯台",
        "name_kana": "おまえざきとうだい",
        "region": "関東・北陸・東海",
        "prefecture": "静岡県",
        "latitude": 34.5939,
        "longitude": 138.2292,
        "description": "駿河湾の入口、御前崎岬に建つ白亜の灯台。1874年（明治7年）初点灯。登れる灯台として人気を誇る。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/03kanku/lighthouse/omaezaki.html",
        "qr_url_pattern": "omaezaki",
        "established_year": 1874,
        "is_climbable": True,
    },
    {
        "id": 11,
        "name": "安乗埼灯台",
        "name_kana": "あのりさきとうだい",
        "region": "関東・北陸・東海",
        "prefecture": "三重県",
        "latitude": 34.4806,
        "longitude": 136.8075,
        "description": "志摩半島の先端、安乗岬に建つ四角形の珍しい灯台。1873年（明治6年）初点灯の登れる灯台。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/04kanku/lighthouse/anori.html",
        "qr_url_pattern": "anori",
        "established_year": 1873,
        "is_climbable": True,
    },
    {
        "id": 12,
        "name": "大王埼灯台",
        "name_kana": "だいおうさきとうだい",
        "region": "関東・北陸・東海",
        "prefecture": "三重県",
        "latitude": 34.2728,
        "longitude": 136.9178,
        "description": "英虞湾の入口、大王崎に建つ灯台。「恋する灯台」に認定されており、カップルに人気の登れる灯台。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/04kanku/lighthouse/daio.html",
        "qr_url_pattern": "daio",
        "established_year": 1927,
        "is_climbable": True,
    },
    {
        "id": 13,
        "name": "神子元島灯台",
        "name_kana": "みこもとじまとうだい",
        "region": "関東・北陸・東海",
        "prefecture": "静岡県",
        "latitude": 34.5644,
        "longitude": 138.9431,
        "description": "伊豆半島南端沖の孤島・神子元島に建つ灯台。英国人技師ブラントンが設計した石造りの灯台で、世界灯台100選にも名を連ねる。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/03kanku/lighthouse/mikamoto.html",
        "qr_url_pattern": "mikamoto",
        "established_year": 1870,
        "is_climbable": False,
    },
    # ── 近畿・中国・四国 ─────────────────────────────────────────────────
    {
        "id": 14,
        "name": "潮岬灯台",
        "name_kana": "しおのみさきとうだい",
        "region": "近畿・中国・四国",
        "prefecture": "和歌山県",
        "latitude": 33.4344,
        "longitude": 135.7656,
        "description": "本州最南端の岬に建つ灯台。1873年（明治6年）初点灯。太平洋の荒波を見渡せる登れる灯台として人気。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/05kanku/lighthouse/shionomi.html",
        "qr_url_pattern": "shionomi",
        "established_year": 1873,
        "is_climbable": True,
    },
    {
        "id": 15,
        "name": "友ヶ島灯台",
        "name_kana": "ともがしまとうだい",
        "region": "近畿・中国・四国",
        "prefecture": "和歌山県",
        "latitude": 34.2822,
        "longitude": 135.0467,
        "description": "紀淡海峡に浮かぶ無人島・沖ノ島に建つ灯台。旧軍の砲台跡が残るラピュタの島として有名。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/05kanku/lighthouse/tomogashima.html",
        "qr_url_pattern": "tomogashima",
        "established_year": 1872,
        "is_climbable": False,
    },
    {
        "id": 16,
        "name": "日御碕灯台",
        "name_kana": "ひのみさきとうだい",
        "region": "近畿・中国・四国",
        "prefecture": "島根県",
        "latitude": 35.4358,
        "longitude": 132.6269,
        "description": "日本一高い石造り灯台（高さ43.65m）。1903年（明治36年）初点灯。出雲大社に近い景勝地に立ち、日本海を見渡す登れる灯台。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/08kanku/lighthouse/hinomisaki.html",
        "qr_url_pattern": "hinomisaki",
        "established_year": 1903,
        "is_climbable": True,
    },
    {
        "id": 17,
        "name": "美保関灯台",
        "name_kana": "みほのせきとうだい",
        "region": "近畿・中国・四国",
        "prefecture": "島根県",
        "latitude": 35.5700,
        "longitude": 133.3231,
        "description": "島根半島最東端に位置する灯台。1898年（明治31年）初点灯。石造りの優美な姿と美保神社への参拝路が人気を呼ぶ登れる灯台。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/08kanku/lighthouse/mihonoseki.html",
        "qr_url_pattern": "mihonoseki",
        "established_year": 1898,
        "is_climbable": True,
    },
    {
        "id": 18,
        "name": "角島灯台",
        "name_kana": "つのしまとうだい",
        "region": "近畿・中国・四国",
        "prefecture": "山口県",
        "latitude": 34.3703,
        "longitude": 130.8578,
        "description": "下関市の角島に建つ石造りの灯台。1876年（明治9年）初点灯。エメラルドグリーンの海に囲まれ、日本屈指の絶景とされる登れる灯台。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/07kanku/lighthouse/tsunoshima.html",
        "qr_url_pattern": "tsunoshima",
        "established_year": 1876,
        "is_climbable": True,
    },
    {
        "id": 19,
        "name": "六連島灯台",
        "name_kana": "むつれじまとうだい",
        "region": "近畿・中国・四国",
        "prefecture": "山口県",
        "latitude": 33.9683,
        "longitude": 130.8883,
        "description": "関門海峡の玄関口にある六連島に建つ灯台。1872年（明治5年）初点灯。日本最初期の洋式灯台の一つ。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/07kanku/lighthouse/mutsure.html",
        "qr_url_pattern": "mutsure",
        "established_year": 1872,
        "is_climbable": False,
    },
    {
        "id": 20,
        "name": "室戸岬灯台",
        "name_kana": "むろとみさきとうだい",
        "region": "近畿・中国・四国",
        "prefecture": "高知県",
        "latitude": 33.2567,
        "longitude": 134.1775,
        "description": "四国最南東端の室戸岬に建つ大型灯台。1899年（明治32年）初点灯。日本最大級の第1等フレネルレンズを備え、登れる灯台として人気。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/05kanku/lighthouse/muroto.html",
        "qr_url_pattern": "muroto",
        "established_year": 1899,
        "is_climbable": True,
    },
    {
        "id": 21,
        "name": "足摺岬灯台",
        "name_kana": "あしずりみさきとうだい",
        "region": "近畿・中国・四国",
        "prefecture": "高知県",
        "latitude": 32.7147,
        "longitude": 133.0031,
        "description": "四国最南端の足摺岬に建つ白い灯台。1914年（大正3年）初点灯。ジョン万次郎ゆかりの地に立つ登れる灯台。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/05kanku/lighthouse/ashizuri.html",
        "qr_url_pattern": "ashizuri",
        "established_year": 1914,
        "is_climbable": True,
    },
    {
        "id": 22,
        "name": "佐田岬灯台",
        "name_kana": "さだみさきとうだい",
        "region": "近畿・中国・四国",
        "prefecture": "愛媛県",
        "latitude": 33.3439,
        "longitude": 132.0025,
        "description": "四国最西端の細長い佐田岬半島の先端に建つ灯台。1918年（大正7年）初点灯。豊後水道を往来する船の安全を守る。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/06kanku/lighthouse/sadamisaki.html",
        "qr_url_pattern": "sadamisaki",
        "established_year": 1918,
        "is_climbable": False,
    },
    # ── 九州・沖縄 ────────────────────────────────────────────────────────
    {
        "id": 23,
        "name": "関埼灯台",
        "name_kana": "せきさきとうだい",
        "region": "九州・沖縄",
        "prefecture": "大分県",
        "latitude": 33.2553,
        "longitude": 131.7564,
        "description": "豊後水道の入口、佐賀関半島の先端に建つ灯台。速吸の瀬戸と呼ばれる激流を行き交う船舶を導く。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/06kanku/lighthouse/sekizaki.html",
        "qr_url_pattern": "sekizaki",
        "established_year": 1901,
        "is_climbable": False,
    },
    {
        "id": 24,
        "name": "都井岬灯台",
        "name_kana": "といみさきとうだい",
        "region": "九州・沖縄",
        "prefecture": "宮崎県",
        "latitude": 31.3789,
        "longitude": 131.1556,
        "description": "野生の岬馬（御崎馬）が生息する都井岬に建つ灯台。1929年（昭和4年）初点灯の登れる灯台で、太平洋を一望できる絶景スポット。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/10kanku/lighthouse/toi.html",
        "qr_url_pattern": "toi",
        "established_year": 1929,
        "is_climbable": True,
    },
    {
        "id": 25,
        "name": "佐多岬灯台",
        "name_kana": "さたみさきとうだい",
        "region": "九州・沖縄",
        "prefecture": "鹿児島県",
        "latitude": 31.0033,
        "longitude": 130.6589,
        "description": "本土最南端・佐多岬沖の小島に建つ灯台。1871年（明治4年）初点灯。日本で最も古い洋式灯台のひとつ。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/10kanku/lighthouse/sata.html",
        "qr_url_pattern": "sata",
        "established_year": 1871,
        "is_climbable": False,
    },
    {
        "id": 26,
        "name": "残波岬灯台",
        "name_kana": "ざんぱみさきとうだい",
        "region": "九州・沖縄",
        "prefecture": "沖縄県",
        "latitude": 26.3953,
        "longitude": 127.6758,
        "description": "沖縄本島中部西海岸の残波岬に建つ灯台。1974年（昭和49年）初点灯。断崖絶壁の上に立つ沖縄最大級の登れる灯台。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/11kanku/lighthouse/zanpa.html",
        "qr_url_pattern": "zanpa",
        "established_year": 1974,
        "is_climbable": True,
    },
    {
        "id": 27,
        "name": "石垣島灯台",
        "name_kana": "いしがきじまとうだい",
        "region": "九州・沖縄",
        "prefecture": "沖縄県",
        "latitude": 24.4533,
        "longitude": 124.1783,
        "description": "石垣島南西端の御神崎に建つ灯台。サンゴ礁と澄み切った海に囲まれ、八重山諸島への玄関口として船舶を導く。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/11kanku/lighthouse/ishigaki.html",
        "qr_url_pattern": "ishigaki",
        "established_year": 1986,
        "is_climbable": False,
    },
    {
        "id": 28,
        "name": "平安名埼灯台",
        "name_kana": "へんなさきとうだい",
        "region": "九州・沖縄",
        "prefecture": "沖縄県",
        "latitude": 24.7764,
        "longitude": 125.4494,
        "description": "宮古島の東端、平安名埼に建つ灯台。1967年（昭和42年）初点灯の登れる灯台で、宮古海峡を行き交う船を見守る。",
        "jcg_page_url": "https://www.kaiho.mlit.go.jp/11kanku/lighthouse/henna.html",
        "qr_url_pattern": "henna",
        "established_year": 1967,
        "is_climbable": True,
    },
]


def seed():
    db = SessionLocal()
    try:
        existing = db.query(Lighthouse).count()
        if existing > 0:
            print(f"既に {existing} 件の灯台データが存在します。スキップします。")
            return

        for data in LIGHTHOUSES:
            lh = Lighthouse(**data)
            db.add(lh)

        db.commit()
        print(f"{len(LIGHTHOUSES)} 件の灯台データを投入しました。")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
